
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: hello
        image: yp3yp3/weather:19
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: weather
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: weather

