replicaCount: 1

image:
  repository: yp3yp3/weather
  tag: 23
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8081 

ingress:
  enabled: true
  hosts:
    - host: test.k8s.yp3yp3.online
      paths:
        - path: /
          pathType: Prefix

env:
  ENV: "test"
